AWSTemplateFormatVersion: '2010-09-09'

Description: Deploy a simple Amazon Linux 2023 EC2 instance

Parameters:

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

Resources:

  EC2Instance:
    Type: AWS::EC2::Instance

    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType

      Tags:
        - Key: Name
          Value: CloudFormation-EC2

Outputs:

  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance

  PublicIP:
    Description: Public IP Address
    Value: !GetAtt EC2Instance.PublicIp