name: Deploy CloudFormation

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  STACK_NAME: ec2-demo

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::544253493985:role/GitHubActionsCloudFormationRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate CloudFormation
        run: |
          aws cloudformation validate-template \
            --template-body file://template.yaml

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file template.yaml \
            --parameter-overrides \
              InstanceType=t2.micro \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Show Stack Outputs
        run: |
          aws cloudformation describe-stacks \
            --stack-name $STACK_NAME